### PR TITLE
fixed bug where custom bbcode loaded no custom code :(

### PR DESCRIPTION
**Pull request by VeekeeFr**

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Thanks! 🍻

**Comment by ThomDietrich** [comment]
Btw your identity is not properly linked by github. You can easily correct that if you care.

**Comment by VeekeeFr** [comment]
Hello :)

Do you mean my identity is VeekeeFr but my commits show veekee ?

**Comment by VeekeeFr** [comment]
fixed it, should be OK now :)

**Comment by ThomDietrich** [comment]
Yes exactly. It's still not resolved. You should be able to click your name here: https://github.com/ThomDietrich/jcomments/commits/master

You need to add the mail address used in the commit to your GitHub settings.

**Pull request merged**
